export const PELICULAS = [
  {
    adult: false,
    backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
    genre_ids: [27, 18, 878],
    id: 933260,
    original_language: "en",
    original_title: "The Substance",
    overview:
      '"Tú, pero mejor en todos los sentidos". Esa es la promesa de La Sustancia, un producto revolucionario basado en la división celular, que crea un alter ego más joven, más bello, más perfecto.',
    popularity: 4964.05,
    poster_path: "/4cJyrYA7I29QabrQ0S89N1iWUV2.jpg",
    release_date: "2024-09-07",
    title: "La Sustancia",
    video: false,
    vote_average: 7.4,
    vote_count: 510,
  },
  {
    adult: false,
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    genre_ids: [28, 35, 878],
    id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview:
      "Un apático Wade Wilson se afana en la vida civil tras dejar atrás sus días como Deadpool, un mercenario moralmente flexible. Pero cuando su mundo natal se enfrenta a una amenaza existencial, Wade debe volver a vestirse a regañadientes con un Lobezno aún más reacio a ayudar.",
    popularity: 2844.462,
    poster_path: "/9TFSqghEHrlBMRR63yTx80Orxva.jpg",
    release_date: "2024-07-24",
    title: "Deadpool y Lobezno",
    video: false,
    vote_average: 7.713,
    vote_count: 4476,
  },
  {
    adult: false,
    backdrop_path: "/xi1VSt3DtkevUmzCx2mNlCoDe74.jpg",
    genre_ids: [35, 14, 27],
    id: 917496,
    original_language: "en",
    original_title: "Beetlejuice Beetlejuice",
    overview:
      "Tras una inesperada tragedia familiar, tres generaciones de la familia Deetz regresan a Winter River. La vida de Lydia, todavía atormentada por Bitelchús, da un vuelco cuando su rebelde hija adolescente, Astrid, descubre la misteriosa maqueta de la ciudad en el desván y el portal al Más Allá se abre accidentalmente. Con los problemas que se avecinan en ambos reinos, es sólo cuestión de tiempo que alguien diga el nombre de Bitelchús tres veces y el travieso demonio regrese para desatar su propio caos.",
    popularity: 1986.658,
    poster_path: "/kWJw7dCWHcfMLr0irTHAPIKrJ4I.jpg",
    release_date: "2024-09-04",
    title: "Bitelchús Bitelchús",
    video: false,
    vote_average: 7.204,
    vote_count: 1289,
  },
  {
    adult: false,
    backdrop_path: "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
    genre_ids: [878, 53, 18, 27],
    id: 1125510,
    original_language: "es",
    original_title: "El hoyo 2",
    overview:
      "Un misterioso líder ha impuesto su ley en un brutal sistema de celdas verticales, pero la llegada de una residente desafía su dudoso método de distribución de comida.",
    popularity: 1948.952,
    poster_path: "/8cnfdskwEmS1HZhenEVYt9P0IYa.jpg",
    release_date: "2024-09-27",
    title: "El hoyo 2",
    video: false,
    vote_average: 5.7,
    vote_count: 545,
  },
  {
    adult: false,
    backdrop_path: "/v9acaWVVFdZT5yAU7J2QjwfhXyD.jpg",
    genre_ids: [16, 878, 10751],
    id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview:
      "Una robot (la unidad ROZZUM 7134 o «Roz») ha naufragado en una isla deshabitada y deberá aprender a adaptarse al duro entorno, forjando poco a poco relaciones con la fauna local y convirtiéndose en madre adoptiva de una cría de ganso huérfana.",
    popularity: 2282.501,
    poster_path: "/sDoXpaKZmrzCSJH63zZvQQ9A7VK.jpg",
    release_date: "2024-09-12",
    title: "Robot salvaje",
    video: false,
    vote_average: 8.562,
    vote_count: 390,
  },
  {
    adult: false,
    backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
    genre_ids: [27, 53],
    id: 1034541,
    original_language: "en",
    original_title: "Terrifier 3",
    overview: 'Secuela de "Terrifier 2", ambientada en el periodo navideño.',
    popularity: 1576.845,
    poster_path: "/5eECVdOWwbsUARVxLA7ENyBYx3H.jpg",
    release_date: "2024-10-09",
    title: "Terrifier 3",
    video: false,
    vote_average: 7,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    genre_ids: [16, 10751, 35, 28],
    id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview:
      "Gru, Lucy y las niñas -Margo, Edith y Agnes- dan la bienvenida a un nuevo miembro en la familia: Gru Junior, que parece llegar con el propósito de ser un suplicio para su padre. Gru tendrá que enfrentarse en esta ocasión a su nueva némesis Maxime Le Mal y su sofisticada y malévola novia Valentina, lo que obligará a la familia a tener que darse a la fuga. Cuarta entrega de 'Gru, mi villano favorito'.",
    popularity: 1339.874,
    poster_path: "/kqph8UWNOoYgTjYnkAx8dRlLLCq.jpg",
    release_date: "2024-06-20",
    title: "Gru 4. Mi villano favorito",
    video: false,
    vote_average: 7.133,
    vote_count: 1977,
  },
  {
    adult: false,
    backdrop_path: "/g1z1ZvYKcmk9EnVOTYXR6vkNjkZ.jpg",
    genre_ids: [14, 27, 28],
    id: 1087822,
    original_language: "en",
    original_title: "Hellboy: The Crooked Man",
    overview:
      "Sigue a Hellboy y a un agente novato de BPRD mientras quedan varados en la zona rural de los Apalaches de la década de 1950. Descubren una pequeña comunidad embrujada por brujas, dirigida por el Hombre Torcido.",
    popularity: 1395.785,
    poster_path: "/ExFaxmvlGxBmUBVKv9ey94fNyy.jpg",
    release_date: "2024-08-29",
    title: "Hellboy: The Crooked Man",
    video: false,
    vote_average: 4.8,
    vote_count: 112,
  },
  {
    adult: false,
    backdrop_path: "/cRdA9xjHBbobw4LJFsQ3j1CgpVq.jpg",
    genre_ids: [27, 53],
    id: 663712,
    original_language: "en",
    original_title: "Terrifier 2",
    overview:
      "Después de ser resucitado por una entidad siniestra, Art the Clown regresa al condado de Miles, donde debe cazar y destruir a una adolescente y a su hermano menor en la noche de Halloween.",
    popularity: 655.32,
    poster_path: "/yw8NQyvbeNXoZO6v4SEXrgQ27Ll.jpg",
    release_date: "2022-10-06",
    title: "Terrifier 2",
    video: false,
    vote_average: 6.8,
    vote_count: 1841,
  },
  {
    adult: false,
    backdrop_path: "/7cjrEMDo2xDT95fvCNb0CssokxZ.jpg",
    genre_ids: [16, 35],
    id: 1358947,
    original_language: "en",
    original_title: "The Most Wonderful Time of the Year",
    overview: "",
    popularity: 573.86,
    poster_path: "/eULRCDZZt7YVCosoqV8j5lnTXyh.jpg",
    release_date: "2024-10-11",
    title: "The Most Wonderful Time of the Year",
    video: false,
    vote_average: 5.8,
    vote_count: 9,
  },
  {
    adult: false,
    backdrop_path: "/naNXYdBzTEb1KwOdi1RbBkM9Zv1.jpg",
    genre_ids: [27, 53],
    id: 420634,
    original_language: "en",
    original_title: "Terrifier",
    overview:
      "El payaso psicópata Art, aterroriza a dos chicas durante la noche de Halloween, matando a todos aquellos que se interponen en su camino.",
    popularity: 652.315,
    poster_path: "/KIIIBoch1WEfghfxuchdk3MnQS.jpg",
    release_date: "2018-01-25",
    title: "Terrifier",
    video: false,
    vote_average: 6.438,
    vote_count: 2160,
  },
  {
    adult: false,
    backdrop_path: "/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg",
    genre_ids: [10749, 18],
    id: 1079091,
    original_language: "en",
    original_title: "It Ends with Us",
    overview:
      "Una mujer atraviesa las tumultuosas etapas de una relación abusiva. Tras mudarse a la ciudad de Boston después de la universidad, decide iniciar su propio negocio como florista y se enamora de un joven neurocirujano.",
    popularity: 545.578,
    poster_path: "/2EH42blLQzgqwDWxn39RXkTgb91.jpg",
    release_date: "2024-08-07",
    title: "Romper el círculo",
    video: false,
    vote_average: 7.163,
    vote_count: 838,
  },
  {
    adult: false,
    backdrop_path: "/vmzauGqSgx25rzavUbuN6c5Vdfc.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 1059264,
    original_language: "en",
    original_title: "The Inseparables",
    overview:
      "Un títere de Don Quijote fugitivo con una imaginación ilimitada, y DJ Doggy Dog, un peluche abandonado que necesita un amigo, cruzarán sus caminos en Central Park y se unirán contra viento y marea para una épica aventura de amistad en la ciudad de Nueva York.",
    popularity: 598.014,
    poster_path: "/kli0m5RLz5m4MdeuNNS2VyUpWrT.jpg",
    release_date: "2023-09-01",
    title: "Héroes de Central Park",
    video: false,
    vote_average: 6.6,
    vote_count: 26,
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: [16, 14, 12],
    id: 823219,
    original_language: "xx",
    original_title: "Flow",
    overview:
      "El mundo parece estar llegando a su fin, repleto de vestigios de presencia humana. Gato es un animal solitario, pero como su hogar es arrasado por una gran inundación, encuentra refugio en un barco poblado por varias especies, y tendrá que hacer equipo con ellas a pesar de sus diferencias. En el solitario barco que navega por místicos paisajes desbordados, navegan por los desafíos y peligros de adaptarse a este nuevo mundo..",
    popularity: 591.824,
    poster_path: "/enRimDhtFfb7hNTQlOjrgK8O8UO.jpg",
    release_date: "2024-08-30",
    title: "Flow",
    video: false,
    vote_average: 8.926,
    vote_count: 101,
  },
  {
    adult: false,
    backdrop_path: "/AowNXLFNKWDRYBKHLsgTK0T7Bxf.jpg",
    genre_ids: [28, 35, 80],
    id: 1210794,
    original_language: "sv",
    original_title: "Strul",
    overview:
      "Un torpe dependiente de electrónica, condenado por un asesinato que no cometió, se enfrenta a policías corruptos y conspiraciones criminales mientras intenta probar su inocencia.",
    popularity: 559.05,
    poster_path: "/aCuEbAjkYk4ROnkluUQ1hO4tGHf.jpg",
    release_date: "2024-10-02",
    title: "Problemas...",
    video: false,
    vote_average: 6.9,
    vote_count: 90,
  },
  {
    adult: false,
    backdrop_path: "/c7K0gjcbUMQdW7DV8kRCi1mmv75.jpg",
    genre_ids: [35, 53, 28],
    id: 877817,
    original_language: "en",
    original_title: "Wolfs",
    overview:
      "Dos “solucionadores” rivales cruzan sus caminos cuando los llaman a ambos para ayudar a ocultar el desliz de una importante funcionaria de Nueva York. Durante una noche muy intensa, deberán dejar de lado sus pequeñas rencillas -y sus egos- para terminar el trabajo.",
    popularity: 510.133,
    poster_path: "/xT3CLqaix8CAhiuXmptJcxwCFBj.jpg",
    release_date: "2024-09-20",
    title: "Wolfs",
    video: false,
    vote_average: 6.6,
    vote_count: 536,
  },
  {
    adult: false,
    backdrop_path: "/5tqkP8NNWdteskVBYPRXE6h82ts.jpg",
    genre_ids: [18],
    id: 592695,
    original_language: "sv",
    original_title: "Pleasure",
    overview:
      "La joven Linnéa deja atrás su vida en un pueblo sueco para ir a Los Angeles y convertirse en la próxima gran estrella porno. El camino hacia su objetivo será más accidentado de lo que había imaginado.",
    popularity: 478.644,
    poster_path: "/eq2JtD4oWJG82zWMaJvzwsV7whK.jpg",
    release_date: "2021-10-08",
    title: "Pleasure",
    video: false,
    vote_average: 6.2,
    vote_count: 528,
  },
  {
    adult: false,
    backdrop_path: "/vGaBqgY8YRzQVUbBMPnd5SmYvL7.jpg",
    genre_ids: [16, 35],
    id: 1329336,
    original_language: "en",
    original_title: "The Bad Guys: Haunted Heist",
    overview:
      "La pícara banda de los tipos malos planea un arriesgadísimo atraco en Halloween de un valioso amuleto en una tenebrosa mansión. ¿Qué podría salir mal?",
    popularity: 611.344,
    poster_path: "/4njXv4s77hq9VGMOquvRQDiu53W.jpg",
    release_date: "2024-10-02",
    title: "Los tipos malos: ¿Truco o atraco?",
    video: false,
    vote_average: 7.3,
    vote_count: 57,
  },
  {
    adult: false,
    backdrop_path: "/1fL2S8LKxCVE9KoPRBXeagmBtex.jpg",
    genre_ids: [27, 53],
    id: 1114513,
    original_language: "en",
    original_title: "Speak No Evil",
    overview:
      "Cuando una familia estadounidense va invitada a pasar un fin de semana en la idílica finca campestre de una encantadora familia británica que conocieron en unas vacaciones, lo que comienza como una escapada de ensueño pronto se convierte en una retorcida pesadilla psicológica.",
    popularity: 547.17,
    poster_path: "/rdGpSGWNnpHuouEJjXOkzbTyRJk.jpg",
    release_date: "2024-09-11",
    title: "No hables con extraños",
    video: false,
    vote_average: 7.354,
    vote_count: 695,
  },
  {
    adult: false,
    backdrop_path: "/l0Y9OzRWKmlzZcGy4olKaOPXsru.jpg",
    genre_ids: [10749, 14, 16],
    id: 3933,
    original_language: "en",
    original_title: "Corpse Bride",
    overview:
      "Ambientada en un pueblecito europeo en el siglo XIX, esta película de animación fotograma a fotograma cuenta la historia de Victor (a quien pone voz Johnny Depp), un joven que es llevado de repente al infierno, donde se casa con una misteriosa Novia Cadáver (con la voz de Helena Bonham Carter), mientras que su verdadera novia, Victoria (a quien pone voz Emily Watson) espera en el mundo de los vivos. A pesar de que la tierra de los muertos resulta ser más colorista que su estricta educación victoriana, Victor aprende que no hay nada en este mundo, ni en el siguiente, que pueda separarle de su único y verdadero amor. Es un cuento de optimismo, romance y una “otra vida” muy animada, contada con el clásico estilo Tim Burton.",
    popularity: 635.027,
    poster_path: "/3ALM0VeZjGUryAqWo6pqohzbLDh.jpg",
    release_date: "2005-09-12",
    title: "La novia cadáver",
    video: false,
    vote_average: 7.569,
    vote_count: 9074,
  },
  {
    adult: false,
    backdrop_path: "/64tinBsds1nVp4wOCgYhMbSgsRW.jpg",
    genre_ids: [28, 18, 36],
    id: 1075676,
    original_language: "ko",
    original_title: "전,란",
    overview:
      "En la dinastía Joseon, dos amigos que crecieron juntos, uno siendo amo y otro siendo esclavo, se reencuentran después de la guerra como adversarios, cada uno en un bando.",
    popularity: 607.522,
    poster_path: "/u7BbfoOND2qtKUslMbPhgHVuVFK.jpg",
    release_date: "2024-10-02",
    title: "Invasión, insurrección",
    video: false,
    vote_average: 7.2,
    vote_count: 59,
  },
  {
    adult: false,
    backdrop_path: "/ansCWyqoyjLEueDXOUZeLrQlZ9J.jpg",
    genre_ids: [28, 80, 53],
    id: 1010161,
    original_language: "en",
    original_title: "The Clean Up Crew",
    overview:
      "Un equipo de limpieza de la escena del crimen descubre un maletín lleno de dinero en efectivo y, sin darse cuenta, es enviado a una batalla con mafiosos, dirigido por un jefe criminal despiadado y corrupto y agentes del gobierno que están empeñados en recuperar el dinero.",
    popularity: 400.955,
    poster_path: "/iiCO3ADeGsFq5clZh52VDBnRInm.jpg",
    release_date: "2024-09-12",
    title: "Dinero sucio",
    video: false,
    vote_average: 5.5,
    vote_count: 4,
  },
  {
    adult: false,
    backdrop_path: "/wh1IhMWkW7u5c5bkzSGFylF9G8r.jpg",
    genre_ids: [28, 80, 53],
    id: 1215162,
    original_language: "en",
    original_title: "Kill 'em All 2",
    overview:
      "Philip y Suzanne, ahora agentes asociados por la CIA, se dirigen a Europa en una nueva misión.",
    popularity: 451.37,
    poster_path: "/rWS8Wo9aN90GcokuvpMNjJYRijA.jpg",
    release_date: "2024-09-24",
    title: "Mátalos a todos 2",
    video: false,
    vote_average: 7,
    vote_count: 105,
  },
  {
    adult: false,
    backdrop_path: "/m1DkRQbNXjs2RYC0FP4r6mdaLCi.jpg",
    genre_ids: [16, 878, 12, 10751, 28],
    id: 698687,
    original_language: "en",
    original_title: "Transformers One",
    overview:
      "La historia jamás contada del origen de Optimus Prime y Megatron y de cómo pasaron de ser hermanos de armas que cambiaron el destino de Cybertron para siempre, a convertirse en enemigos acérrimos.",
    popularity: 457.914,
    poster_path: "/ynqqkPy8RiawjGtWFIsF9pmYZtJ.jpg",
    release_date: "2024-09-11",
    title: "Transformers One",
    video: false,
    vote_average: 7.477,
    vote_count: 154,
  },
  {
    adult: false,
    backdrop_path: "/igtm12Wy9EUlxFeyb4v8bRyuYSY.jpg",
    genre_ids: [28, 80, 18, 53],
    id: 1337309,
    original_language: "th",
    original_title: "Bangkok Breaking: ฝ่านรกเมืองเทวดา",
    overview:
      "Un rescatista debe luchar por sobrevivir tras verse atrapado en un conflicto entre bandas rivales de los bajos fondos de Bangkok.",
    popularity: 433.981,
    poster_path: "/45Yxq9aEfMgPEq6bGZG0BgbDQge.jpg",
    release_date: "2024-09-26",
    title: "Corrupción en Bangkok: Entre el cielo y el infierno",
    video: false,
    vote_average: 6.5,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: "/z8muwOfNZ4qivqgASnIkeeHSSX3.jpg",
    genre_ids: [27],
    id: 1089123,
    original_language: "en",
    original_title: "Daddy's Head",
    overview: "",
    popularity: 390.662,
    poster_path: "/77vlYgTiqeZ3khLmPQqrqKX2FU6.jpg",
    release_date: "2024-10-10",
    title: "Daddy's Head",
    video: false,
    vote_average: 5.6,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/mKOBdgaEFguADkJhfFslY7TYxIh.jpg",
    genre_ids: [28, 878, 35],
    id: 365177,
    original_language: "en",
    original_title: "Borderlands",
    overview:
      "Lilith, una infame cazatesoros con un misterioso pasado, regresa a su planeta natal de Pandora para encontrar a la hija desaparecida del poderoso Atlas. Para ello forma una alianza inesperada con un heterogéneo equipo de inadaptados: Roland, un antiguo mercenario de élite ahora desesperado por la redención; Tiny Tina, una demolicionista salvaje preadolescente; Krieg, el musculoso protector de Tina; la científica Tannis; y Claptrap, un robot muy peculiar. Estos extraños héroes deberán luchar contra monstruos alienígenas y peligrosos bandidos para buscar y proteger a la niña desaparecida, que puede tener la clave de un poder inimaginable.",
    popularity: 399.007,
    poster_path: "/jtEZi4eZxDjxcDIeMbkQ8HmvRs1.jpg",
    release_date: "2024-08-07",
    title: "Borderlands",
    video: false,
    vote_average: 5.842,
    vote_count: 691,
  },
  {
    adult: false,
    backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
    genre_ids: [28, 12, 53, 80],
    id: 7451,
    original_language: "en",
    original_title: "xXx",
    overview:
      'Xander Cage es XXX, un antiguo ganador de X-Games y atleta profesional de deportes de extremo, que sobrevive vendiendo videos de sus increíbles hazañas, las cuales hacen emitir adrenalina por todo el cuerpo. Pero después de incontables encuentros con la ley, su mundo está a punto de tomar un rumbo aún más extremo... Porque Xander no sabe que ha sido "espiado" por Augustus Gibbons, un agente veterano de la Agencia Nacional de Seguridad que se encuentra en una desesperada situación en la distante ciudad de Praga, en donde su operativo secreto ha sido asesinado por una pandilla de mafiosos con un estilo muy propio, que se llaman así mismos Anarchy 99, encabezados por el brutal ex-Comandante del Ejército Ruso Yorgi.',
    popularity: 325.866,
    poster_path: "/gd4hRY3pFXRY7YVbMdVBpnKV7wC.jpg",
    release_date: "2002-08-09",
    title: "xXx",
    video: false,
    vote_average: 5.933,
    vote_count: 4230,
  },
  {
    adult: false,
    backdrop_path: "/VuukZLgaCrho2Ar8Scl9HtV3yD.jpg",
    genre_ids: [878, 28],
    id: 335983,
    original_language: "en",
    original_title: "Venom",
    overview:
      "Eddie Brock es un consolidado periodista y astuto reportero que está investigando una empresa llamada Fundación Vida. Esta fundación, dirigida por el eminente científico Carlton Drake, está ejecutando secretamente experimentos ilegales en seres humanos y realizando pruebas que involucran formas de vida extraterrestres y amorfas conocidas como simbiontes. Durante una visita furtiva a la central, el periodista quedará infectado por un simbionte. Comenzará entonces a experimentar cambios en su cuerpo que no entiende, y escuchará una voz interior, la del simbionte Venom, que le dirá lo que tiene que hacer. Cuando Brock adquiera los poderes del simbionte que le usa como huésped, Venom tomará posesión de su cuerpo, convirtiéndole en un despiadado y peligroso súpervillano.",
    popularity: 425.779,
    poster_path: "/jMBTJQiHAyGlZR05J2sq5coA6ew.jpg",
    release_date: "2018-09-28",
    title: "Venom",
    video: false,
    vote_average: 6.828,
    vote_count: 15726,
  },
  {
    adult: false,
    backdrop_path: "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
    genre_ids: [28, 12, 53],
    id: 718821,
    original_language: "en",
    original_title: "Twisters",
    overview:
      "Kate Carter, una ex cazadora de tormentas perseguida por un devastador encuentro con un tornado, es llamada por su amigo Javi de regreso a las llanuras para probar un nuevo e innovador sistema de seguimiento. Allí, se cruza con el encantador e imprudente ídolo de las redes sociales Tyler Owens y su estridente equipo. A medida que la temporada de tormentas se intensifica, se desatan fenómenos terroríficos nunca vistos, y Kate, Tyler y sus equipos competidores se encuentran directamente en el camino de múltiples sistemas de tormentas que convergen sobre Oklahoma en lo que será una lucha por sobrevivir.",
    popularity: 364.339,
    poster_path: "/50xgtaDR0xJkLSVghdTGUeMoPHP.jpg",
    release_date: "2024-07-10",
    title: "Twisters",
    video: false,
    vote_average: 7,
    vote_count: 1593,
  },
  {
    adult: false,
    backdrop_path: "/of1tQasFGCeHgWPmSgdA1WS6hNW.jpg",
    genre_ids: [80, 53, 28],
    id: 1047373,
    original_language: "en",
    original_title: "The Silent Hour",
    overview:
      "Sigue a un detective de policía con discapacidad auditiva que trabaja como intérprete para el departamento y debe enfrentarse a un equipo de policías corruptos que intentan eliminar a un testigo de asesinato sordo en un edificio de apartamentos.",
    popularity: 476.86,
    poster_path: "/ceaZXRjJi8szsnJnQUje3eugtH9.jpg",
    release_date: "2024-10-03",
    title: "The Silent Hour",
    video: false,
    vote_average: 6.8,
    vote_count: 24,
  },
  {
    adult: false,
    backdrop_path: "/nxxCPRGTzxUH8SFMrIsvMmdxHti.jpg",
    genre_ids: [35, 14, 10751],
    id: 639720,
    original_language: "en",
    original_title: "IF",
    overview:
      "Una niña pasa por una experiencia difícil y entonces empieza a ver a los amigos imaginarios de todo el mundo que se han ido quedando atrás a medida que sus amigos de la vida real han ido creciendo.",
    popularity: 410.838,
    poster_path: "/8RgGuC7w8JxhykauzTC4bwha1J8.jpg",
    release_date: "2024-05-08",
    title: "Amigos imaginarios",
    video: false,
    vote_average: 7.279,
    vote_count: 947,
  },
  {
    adult: false,
    backdrop_path: "/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg",
    genre_ids: [10749, 18],
    id: 1010581,
    original_language: "es",
    original_title: "Culpa mía",
    overview:
      "Noah debe dejar su ciudad, novio y amigos para mudarse a la mansión de William Leister, el flamante y rico marido de su madre Rafaela. Por otro lado, con 17 años, orgullosa e independiente, Noah se resiste a vivir en una mansión rodeada de lujo. Allí conoce a Nick, su nuevo hermanastro, y el choque de sus fuertes personalidades se hace evidente desde el primer momento.",
    popularity: 362.819,
    poster_path: "/gp31EwMH5D2bftOjscwkgTmoLAB.jpg",
    release_date: "2023-06-08",
    title: "Culpa mía",
    video: false,
    vote_average: 7.918,
    vote_count: 2976,
  },
  {
    adult: false,
    backdrop_path: "/iHYh4cdO8ylA3W0dUxTDVdyJ5G9.jpg",
    genre_ids: [878, 12, 28],
    id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview:
      "Ambientada varias generaciones en el futuro tras el reinado de César, en la que los simios son la especie dominante que vive en armonía y los humanos se han visto reducidos a vivir en la sombra. Mientras un nuevo y tiránico líder simio construye su imperio, un joven simio emprende un angustioso viaje que le llevará a cuestionarse todo lo que sabe sobre el pasado y a tomar decisiones que definirán el futuro de simios y humanos por igual.",
    popularity: 356.63,
    poster_path: "/kkFn3KM47Qq4Wjhd8GuFfe3LX27.jpg",
    release_date: "2024-05-08",
    title: "El reino del planeta de los simios",
    video: false,
    vote_average: 7.116,
    vote_count: 3056,
  },
  {
    adult: false,
    backdrop_path: "/6XjMwQTvnICBz6TguiDKkDVHvgS.jpg",
    genre_ids: [27, 878, 53],
    id: 762441,
    original_language: "en",
    original_title: "A Quiet Place: Day One",
    overview:
      "Una mujer llamada Sam trata de sobrevivir a una invasión en la ciudad de Nueva York por criaturas alienígenas sedientas de sangre con oídos ultrasónicos. Tercera entrega de la saga y precuela de las dos anteriores.",
    popularity: 366.578,
    poster_path: "/oEfFnOpVCsK1ifcOZTF4s2n7r5N.jpg",
    release_date: "2024-06-26",
    title: "Un lugar tranquilo: Día uno",
    video: false,
    vote_average: 6.793,
    vote_count: 1972,
  },
  {
    adult: false,
    backdrop_path: "/1wP1phHo2CROOqzv7Azs0MT5esU.jpg",
    genre_ids: [16, 35, 10751, 12, 28],
    id: 748783,
    original_language: "en",
    original_title: "The Garfield Movie",
    overview:
      "El mundialmente famoso Garfield, el gato casero que odia los lunes y que adora la lasaña, está a punto de vivir una aventura ¡en el salvaje mundo exterior! Tras una inesperada reunión con su largamente perdido padre – el desaliñado gato callejero Vic – Garfield y su amigo canino Odie se ven forzados a abandonar sus perfectas y consentidas vidas al unirse a Vic en un hilarante y muy arriesgado atraco.",
    popularity: 379.218,
    poster_path: "/tkdc73JiPVvzngSpbLEIfFNjll1.jpg",
    release_date: "2024-04-30",
    title: "Garfield: La película",
    video: false,
    vote_average: 7.119,
    vote_count: 1027,
  },
  {
    adult: false,
    backdrop_path: "/ujkVmpItWDLSkDCc7flsPywJhle.jpg",
    genre_ids: [27],
    id: 1128941,
    original_language: "en",
    original_title: "The Demon Disorder",
    overview: "",
    popularity: 384.04,
    poster_path: "/Oqlmo1bhDQWWBPrMxMauuHL7y7.jpg",
    release_date: "2024-08-16",
    title: "The Demon Disorder",
    video: false,
    vote_average: 5.2,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/p4INKu77iuTG1o1a5N3Y9vqeEGq.jpg",
    genre_ids: [27, 53],
    id: 1079485,
    original_language: "en",
    original_title: "Winnie-the-Pooh: Blood and Honey 2",
    overview:
      "En lo más profundo del Bosque de los Cien Acres, crece una furia destructiva cuando Winnie-the-Pooh, Piglet, Owl y Tigger ven peligrar su hogar y sus vidas después de que Christopher Robin revelara su existencia. No queriendo seguir viviendo en la sombra, el grupo decide llevar la lucha al pueblo de Ashdown, hogar de Christopher Robin, dejando un sangriento rastro de muerte y caos a su paso. Winnie y sus salvajes amigos demostrarán a todo el mundo que son más mortíferos, más fuertes y más listos de lo que nadie podría imaginar y conseguirán vengarse de Christopher Robin, de una vez por todas.",
    popularity: 441.475,
    poster_path: "/17UmQl8TuDmHWGlcKeFIjnR8bJF.jpg",
    release_date: "2024-03-26",
    title: "Winnie de Pooh: Miel y Sangre 2",
    video: false,
    vote_average: 6.3,
    vote_count: 235,
  },
  {
    adult: false,
    backdrop_path: "/askg3SMvhqEl4OL52YuvdtY40Yb.jpg",
    genre_ids: [10751, 16, 10402, 12],
    id: 354912,
    original_language: "en",
    original_title: "Coco",
    overview:
      "Un joven aspirante a músico llamado Miguel se embarca en un viaje extraordinario a la mágica tierra de sus ancestros. Allí, el encantador embaucador Héctor se convierte en su inesperado amigo y le ayuda a descubrir los misterios detrás de las historias y tradiciones de su familia.",
    popularity: 356.821,
    poster_path: "/lUZZhYLLDU4g4XGQ5tvjYNVytxc.jpg",
    release_date: "2017-10-27",
    title: "Coco",
    video: false,
    vote_average: 8.212,
    vote_count: 19272,
  },
  {
    adult: false,
    backdrop_path: "/yRKyJJYIzfeiVDHBe4LXguPQCvD.jpg",
    genre_ids: [14, 35],
    id: 4011,
    original_language: "en",
    original_title: "Beetlejuice",
    overview:
      "¿Qué debería hacer una pareja de fantasmas si su estrafalario hogar de Nueva Inglaterra se llenara de elegantes visitantes neoyorquinos? Pedir ayuda a un exorcista para aterrorizar a los intrusos con el fin de que abandonen la casa. Bitelchús es una criatura de ultratumba repugnante y terrorífica, un fenómeno asustando y bromeando que se gira y se transforma en grotescas formas, traga insectos y no puede dejar a las mujeres (vivas o muertas) en paz.",
    popularity: 309.615,
    poster_path: "/2LanWSlqSOtyvQiIaoYz448oBSl.jpg",
    release_date: "1988-03-30",
    title: "Bitelchús",
    video: false,
    vote_average: 7.38,
    vote_count: 7349,
  },
  {
    adult: false,
    backdrop_path: "/1U7EVGj7Noc26owNOreCTKn59Bd.jpg",
    genre_ids: [27],
    id: 86328,
    original_language: "en",
    original_title: "Terrifier",
    overview: "",
    popularity: 354.758,
    poster_path: "/uP5k78WkCVrxrFp4AJflHbC61Ao.jpg",
    release_date: "2011-08-09",
    title: "Terrifier",
    video: false,
    vote_average: 6.275,
    vote_count: 158,
  },
  {
    adult: false,
    backdrop_path: "/vbAIe8DgAfrhkfwK8uiujXQEIoZ.jpg",
    genre_ids: [18, 9648, 53, 878],
    id: 863873,
    original_language: "en",
    original_title: "Caddo Lake",
    overview:
      "Cuando una niña de ocho años desaparece misteriosamente en Caddo Lake, una serie de muertes y desapariciones del pasado empiezan a mezclarse, alterando para siempre la historia de una familia rota.",
    popularity: 316.126,
    poster_path: "/wQSLDy6H3Wyhf7Z7TNM87y4giez.jpg",
    release_date: "2024-10-09",
    title: "Los horrores de Caddo Lake",
    video: false,
    vote_average: 7.3,
    vote_count: 157,
  },
  {
    adult: false,
    backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
    genre_ids: [28, 12, 878],
    id: 786892,
    original_language: "en",
    original_title: "Furiosa: A Mad Max Saga",
    overview:
      "En un mundo postapocalíptico donde todo ha perdido su valor, los pocos supervivientes se guían por la ley del más fuerte. Sin aprecio por la vida, lo único que despierta un brutal interés es la gasolina, sinónimo de poder y objetivo de bandas armadas hasta los dientes y sin escrúpulos. En este contexto conoceremos la  historia de la arrebatadoramente despiadada, salvaje y joven Furiosa, quien cae en manos de una horda de motoristas y debe sobrevivir a muchas pruebas mientras reúne los medios para encontrar el camino de vuelta a casa. Precuela de 'Mad Max: Furia en la carretera' (2015).",
    popularity: 300.484,
    poster_path: "/tGHUlykWn9V2IIQ4ZaATIAq9VLB.jpg",
    release_date: "2024-05-22",
    title: "Furiosa: De la saga Mad Max",
    video: false,
    vote_average: 7.549,
    vote_count: 3278,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "Eddie Brock  y su simbionte Venom todavía están intentando descubrir cómo vivir juntos cuando un preso que está en el corredor de la muerte se infecta con un simbionte propio.",
    popularity: 351.03,
    poster_path: "/b0j9rHYpRML7dKm5xw9e97HTDJF.jpg",
    release_date: "2021-09-30",
    title: "Venom: habrá matanza",
    video: false,
    vote_average: 6.796,
    vote_count: 9978,
  },
];
export const GENEROS = [
    {
      id: 28,
      name: "Acción",
    },
    {
      id: 12,
      name: "Aventura",
    },
    {
      id: 16,
      name: "Animación",
    },
    {
      id: 35,
      name: "Comedia",
    },
    {
      id: 80,
      name: "Crimen",
    },
    {
      id: 99,
      name: "Documental",
    },
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10751,
      name: "Familia",
    },
    {
      id: 14,
      name: "Fantasía",
    },
    {
      id: 36,
      name: "Historia",
    },
    {
      id: 27,
      name: "Terror",
    },
    {
      id: 10402,
      name: "Música",
    },
    {
      id: 9648,
      name: "Misterio",
    },
    {
      id: 10749,
      name: "Romance",
    },
    {
      id: 878,
      name: "Ciencia ficción",
    },
    {
      id: 10770,
      name: "Película de TV",
    },
    {
      id: 53,
      name: "Suspense",
    },
    {
      id: 10752,
      name: "Bélica",
    },
    {
      id: 37,
      name: "Western",
    },
  ];
export function getFilmById(id) {
  return PELICULAS.find((pelicula) => pelicula.id == id);
}
export function getGenreById(id) {
    return GENEROS.find((genero) => genero.id == id).name;
  }
